### PR TITLE
Created code of conduct to imply rules

### LINKED ISSUE #16: Missing Documentation about Rules
Write some documentation about existing Rules.
Describe what the rule is matching, and provide some example use case.

### PR DESCRIPTION
**Pull request by Notradame**
fixes #16

### CODE REVIEW

**Comment by bigfoot90** [comment]
Plerase remove `Definitions` section

**Comment by Notradame** [comment]
Done

**Comment by bigfoot90** [comment]
Thanks

**Comment by Notradame** [comment]
You're Wecome. ;-)

**Pull request merged**
